version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers
    steps:
      - checkout
      - run: composer install --prefer-dist --no-interaction
      - run: php ./vendor/bin/codecept run unit