version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers
    steps:
      - checkout
      - run: sudo apt --allow-releaseinfo-change update && sudo apt install -y libgmp-dev
      - run: sudo -E docker-php-ext-install gmp bcmath
      - run: COMPOSER_MEMORY_LIMIT=2G composer install --prefer-dist --no-interaction
      - run: php ./vendor/bin/codecept run unit