version: 2
jobs:
  build:
    docker:
      - image: cimg/php:7.4-node
    steps:
      - checkout
      - run: sudo -E install-php-extensions gmp bcmath
      - run: composer install --prefer-dist --no-interaction
      - run: php ./vendor/bin/codecept run unit